"""Public package for the PropertyRadar API client."""

from importlib.metadata import PackageNotFoundError, version

from .buyer_transfer import (
    BUYER_TRANSFER_MATCH_CONTRACT,
    BUYER_TRANSFER_PROPERTY_FIELDS,
    BuyerTransferBillingEvidence,
    BuyerTransferBillingStatus,
    BuyerTransferLinkage,
    BuyerTransferLinkageRelationship,
    BuyerTransferMatchCriteria,
    BuyerTransferMatchResult,
    BuyerTransferProperty,
    BuyerTransferPropertyField,
    BuyerTransferPropertyType,
    BuyerTransferPublicationWindow,
    BuyerTransferRecordingWindow,
    build_buyer_transfer_match_criteria,
    buyer_transfer_scope_fingerprint,
    parse_buyer_transfer_match,
)
from .client import PropertyRadarClient
from .exceptions import (
    AuthenticationError,
    BadRequestError,
    ChargeNotAllowedError,
    ConfigurationError,
    ConflictError,
    ForbiddenError,
    InvalidResponseError,
    MutationNotAllowedError,
    NetworkError,
    NotFoundError,
    PaymentRequiredError,
    PropertyRadarError,
    PropertyRadarHTTPError,
    RateLimitError,
    RequestTimeoutError,
    ServerError,
    ValidationError,
)
from .transaction_history import (
    PROPERTY_PERSON_IDENTITY_FIELDS,
    TRANSACTION_HISTORY_CONTRACT,
    TRANSACTION_HISTORY_FIELDS,
    PropertyOwnershipRole,
    PropertyPersonIdentityField,
    ProviderPersonType,
    TransactionBillingEvidence,
    TransactionBillingStatus,
    TransactionHistory,
    TransactionHistoryField,
    TransactionHistoryRecord,
    TransactionHistoryStatus,
    TransactionParty,
    TransactionPartyKind,
    parse_transaction_history,
)
from .types import (
    Criterion,
    ImportItem,
    JSONDict,
    JSONValue,
    ResponseEnvelope,
    StatusLabelsResponse,
)

try:
    __version__ = version("property-radar")
except PackageNotFoundError:  # pragma: no cover - source tree without an install
    __version__ = "0+unknown"

__all__ = [
    "BUYER_TRANSFER_MATCH_CONTRACT",
    "BUYER_TRANSFER_PROPERTY_FIELDS",
    "PROPERTY_PERSON_IDENTITY_FIELDS",
    "TRANSACTION_HISTORY_CONTRACT",
    "TRANSACTION_HISTORY_FIELDS",
    "AuthenticationError",
    "BadRequestError",
    "BuyerTransferBillingEvidence",
    "BuyerTransferBillingStatus",
    "BuyerTransferLinkage",
    "BuyerTransferLinkageRelationship",
    "BuyerTransferMatchCriteria",
    "BuyerTransferMatchResult",
    "BuyerTransferProperty",
    "BuyerTransferPropertyField",
    "BuyerTransferPropertyType",
    "BuyerTransferPublicationWindow",
    "BuyerTransferRecordingWindow",
    "ChargeNotAllowedError",
    "ConfigurationError",
    "ConflictError",
    "Criterion",
    "ForbiddenError",
    "ImportItem",
    "InvalidResponseError",
    "JSONDict",
    "JSONValue",
    "MutationNotAllowedError",
    "NetworkError",
    "NotFoundError",
    "PaymentRequiredError",
    "PropertyOwnershipRole",
    "PropertyPersonIdentityField",
    "PropertyRadarClient",
    "PropertyRadarError",
    "PropertyRadarHTTPError",
    "ProviderPersonType",
    "RateLimitError",
    "RequestTimeoutError",
    "ResponseEnvelope",
    "ServerError",
    "StatusLabelsResponse",
    "TransactionBillingEvidence",
    "TransactionBillingStatus",
    "TransactionHistory",
    "TransactionHistoryField",
    "TransactionHistoryRecord",
    "TransactionHistoryStatus",
    "TransactionParty",
    "TransactionPartyKind",
    "ValidationError",
    "__version__",
    "build_buyer_transfer_match_criteria",
    "buyer_transfer_scope_fingerprint",
    "parse_buyer_transfer_match",
    "parse_transaction_history",
]
